name: flutter_azure_liveness_example
description: Demonstrates how to use the flutter_azure_liveness plugin.
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_azure_liveness:
    path: ../
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
